name: rapidoc_maps_plugin
description: A private package used as a plugin to support both mobile and web versions of Google maps and some of its services
version: 0.0.5
homepage: "https://web.rapidoc.app"
repository: "https://github.com/Oualitsen/rapidoc_maps_plugin"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.4.0+3
  flutter_responsive_tools: ^0.0.1
  geolocator: ^9.0.2
  infinite_scroll_list_view: ^1.0.0
  dio: ^4.0.4
  rxdart: ^0.27.3
  json_serializable: ^6.1.4
  http_error_handler: ^0.0.1
  retrofit: ^3.0.1
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  retrofit_generator: ^4.0.1

flutter:


